# Generated by Django 3.1.3 on 2020-12-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
        migrations.AddField(
            model_name='users',
            name='enrollCode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='course.group'),
            preserve_default=False,
        ),
    ]
