# Generated by Django 3.1.4 on 2020-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_fisier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisier',
            name='fisier',
            field=models.FileField(upload_to='groups/'),
        ),
        migrations.AlterField(
            model_name='fisier',
            name='title',
            field=models.CharField(blank=True, default='ceva', max_length=50),
        ),
    ]
