# Generated by Django 3.1.3 on 2020-12-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201212_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
