# Generated by Django 3.1.3 on 2020-11-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201126_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
