# Generated by Django 3.1.3 on 2020-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201209_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
